---
- hosts: all
  become: true
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm
    block:
      - name: Check status
        shell: /usr/local/bin/kubectl cluster-info
        environment:
          KUBECONFIG: "/etc/kubernetes/admin.conf"
    rescue:
      - name: Initialize the Kubernetes cluster using kubeadm
        shell: '/usr/local/bin/kubeadm init --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}"  --node-name k8s-master --pod-network-cidr=192.168.50.0/24'
        environment:
          PATH: "{{ ansible_env.PATH }}:/usr/local/bin/"

      - name: Setup kubeconfig for vagrant user
        command: "{{ item }}"
        with_items:
         - mkdir -p /home/vagrant/.kube
         - cp -f /etc/kubernetes/admin.conf /home/vagrant/.kube/config
         - cp -f /etc/kubernetes/admin.conf /vagrant/kubernetes-setup/
         - chown vagrant:vagrant /home/vagrant/.kube/config

      - name: Install flannel pod network
        shell: /usr/local/bin/kubectl apply -f /vagrant/kubernetes-setup/calico.yaml
        environment:
          KUBECONFIG: "/etc/kubernetes/admin.conf"

      - name: Generate join command
        shell: /usr/local/bin/kubeadm token create --print-join-command
        environment:
          KUBECONFIG: "/etc/kubernetes/admin.conf"
        register: join_command

      - name: Copy join command to local file
        local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

