- hosts: all
  tasks:
    - name: Build docker image
      community.docker.docker_image:
        name: registry:5000/hello-spa
        push: yes
        build:
          dockerfile: /app/hello-spa/docker/Dockerfile
          path: /app/hello-spa/
        source: build
      register: out
    - debug: var=out

    - name: Archive image
      community.docker.docker_image:
        name: registry:5000/hello-spa
        tag: latest
        archive_path: /app/hello-spa/docker/hello-spa.tar
        source: local
      register: out
    - debug: var=out
